# Generated by Django 2.2.2 on 2019-06-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiticas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arroba', models.CharField(max_length=50)),
                ('nombre_cuenta', models.CharField(max_length=50)),
            ],
        ),
    ]
